spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://zafry:Zafrymim2000%23@cluster0.czwm7ss.mongodb.net/feedbacktest?retryWrites=true&w=majority&appName=Cluster0}
spring.data.mongodb.auto-index-creation=true
server.port=8080